### PR TITLE
#167945839 Edit README.md

### PR DESCRIPTION
**Pull request by drayzii**
#### Description of Task to be completed?
Add the Documentation Of The API Endpoints
#### How should this be manually tested?
Change the branch to ch-edit-readme-167945839 and go the `README.md` Section
#### Any background context you want to provide?
Request Bodies and Responses examples of the endpoints are provided
#### What are the relevant pivotal tracker stories?
[#167945839](https://www.pivotaltracker.com/story/show/167945839)

### CODE REVIEW

**Comment by j0flintking02** [comment]
Ya, this is nice work but the responses are missing the messages and the JSON is not formatted correctly. You could create something like this.
```json
{
    "status": 200,
    "message": "Account has been created successfully",
    "data": {
        "id": 324,
        "name": "NextProduct",
        "description": "NEXTPRODUCT allows an individual or a group of individuals to vote on the product that they feel are in line with their values, so that they can decide to support",
        "votes": 52,
        "image": "https://res.cloudinary.com/drayzii/image/upload/v1565290420/fssr8ssftpgqqg6p2d7k.png",
        "createdAt": "2019-08-16 21:58:12.578 +00:00",
        "updatedAt": "2019-08-17 21:58:12.578 +00:00"
    }
}
```
and if you could squash your commits into one commit

**Review by willywax — APPROVED** [review]
Looks good to me.

**Review by j0flintking02 — APPROVED** [review]
LGTM

**Review by Dkabiswa — APPROVED** [review]
this is ok

**Pull request merged**
