### PR TITLE
#167944569 User can view a single product

### PR DESCRIPTION
**Pull request by Dkabiswa**
#### What does this PR do?
Add a feature for the user to view a single product.
#### Description of Task to be completed?
- Find a product in the database using its id.
- Return the product to the user.
#### How should this be manually tested?
- Clone this repo and checkout to this branch
- Run `npm run dev`
- Singup or Signin to get token
- Add product into the database
- Visit http://127.0.0.1:5000/api/v1/products/:id
- See if the product is returned
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#167944569 ](https://www.pivotaltracker.com/story/show/167944569)
#### Screenshots (if appropriate)
Screen Shot 2019-08-22 at 08 32 25
Screen Shot 2019-08-22 at 08 32 53

### CODE REVIEW

**Review by Bahatiroben — APPROVED** [review]
this seems great

**Review by drayzii — APPROVED** [review]
Looks Good

**Review by j0flintking02 — APPROVED** [review]
LGTM

**Review by willywax — APPROVED** [review]
Looks Good

**Pull request merged**
