### PR TITLE
#167944540: Implement the update product endpoint

### PR DESCRIPTION
**Pull request by drayzii**
#### What does this PR do?
Implements update product endpoint
#### Description of Task to be completed?
- Wrote the endpoint
- Write tests for the endpoint
#### How should this be manually tested?
- Checkout this branch
- Make a `PATCH` request to `api/v1/products/:id`. Refer to the body in screenshots
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#167944540](https://www.pivotaltracker.com/story/show/167944540)
#### Screenshots (if appropriate)
image

#### Questions:
N/A

### CODE REVIEW

**Review by willywax — COMMENTED** [review]
Try updating a product by passing a wrong/ Invalid token.

**Review by Bahatiroben — CHANGES_REQUESTED** [review]
the middleware incharge of checking authentication (protecting the routes) seems not working as intended. So, please look into changing it to function well.   It looks like when you pass a wrong token, invalid token, or token which has no Bearer before it or token which is  not separated from bearer, the server hangs.

**Review by willywax — APPROVED** [review]
Looks Good

**Review by Bahatiroben — APPROVED** [review]
Yeah it is okay now. All changes have been implemented.

**Pull request merged**
